package adzuna
import ("context";"encoding/json";"fmt";"io";"net/http";"net/url";"os";"strconv";"strings";"time";"jobsearcher/internal/domain";"jobsearcher/internal/sources")
const defaultBase="https://api.adzuna.com/v1/api"
type Client struct{HTTPClient *http.Client;BaseURL string;AppID string;AppKey string}
func NewClient()*Client{return &Client{HTTPClient:&http.Client{Timeout:30*time.Second},BaseURL:defaultBase,AppID:strings.TrimSpace(os.Getenv("ADZUNA_APP_ID")),AppKey:strings.TrimSpace(os.Getenv("ADZUNA_APP_KEY"))}}
func(c *Client)Name()string{return "adzuna"}
type response struct{Results []posting `json:"results"`}
type posting struct{ID string `json:"id"`;Title string `json:"title"`;Description string `json:"description"`;RedirectURL string `json:"redirect_url"`;Created string `json:"created"`;Company struct{DisplayName string `json:"display_name"`} `json:"company"`;Location struct{DisplayName string `json:"display_name"`} `json:"location"`;ContractType string `json:"contract_type"`;ContractTime string `json:"contract_time"`;SalaryMin float64 `json:"salary_min"`;SalaryMax float64 `json:"salary_max"`}
func(c *Client)FetchJobs(ctx context.Context,q sources.Query)([]domain.Job,error){if c.AppID==""||c.AppKey==""{return nil,fmt.Errorf("Adzuna disabled: set ADZUNA_APP_ID and ADZUNA_APP_KEY")};terms:=uniqueTerms(q.Terms);if len(terms)>4{terms=terms[:4]};out:=[]domain.Job{};for _,term:=range terms{jobs,err:=c.fetchTerm(ctx,term);if err!=nil{return out,fmt.Errorf("adzuna term %q: %w",term,err)};out=append(out,jobs...)};return out,nil}
func(c *Client)fetchTerm(ctx context.Context,term string)([]domain.Job,error){u,err:=url.Parse(c.BaseURL+"/jobs/br/search/1");if err!=nil{return nil,err};q:=u.Query();q.Set("app_id",c.AppID);q.Set("app_key",c.AppKey);q.Set("results_per_page","50");q.Set("what",term);q.Set("content-type","application/json");u.RawQuery=q.Encode();req,err:=http.NewRequestWithContext(ctx,http.MethodGet,u.String(),nil);if err!=nil{return nil,err};req.Header.Set("Accept","application/json");req.Header.Set("User-Agent","JobSearcher/1.0");resp,err:=c.HTTPClient.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();body,err:=io.ReadAll(io.LimitReader(resp.Body,32<<20));if err!=nil{return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{return nil,fmt.Errorf("HTTP %d",resp.StatusCode)};var raw response;if err:=json.Unmarshal(body,&raw);err!=nil{return nil,err};out:=make([]domain.Job,0,len(raw.Results));for _,p:=range raw.Results{if p.ID==""||p.Title==""{continue};out=append(out,normalize(p))};return out,nil}
func normalize(p posting)domain.Job{salary:="";if p.SalaryMin>0||p.SalaryMax>0{salary=strconv.FormatFloat(p.SalaryMin,'f',0,64)+" - "+strconv.FormatFloat(p.SalaryMax,'f',0,64)};return domain.Job{ID:"adzuna:"+p.ID,Source:"adzuna",Title:strings.TrimSpace(p.Title),Company:strings.TrimSpace(p.Company.DisplayName),URL:strings.TrimSpace(p.RedirectURL),Location:strings.TrimSpace(p.Location.DisplayName),EmploymentType:strings.TrimSpace(p.ContractTime+" "+p.ContractType),Description:strings.TrimSpace(p.Description),Salary:salary,PostedAt:strings.TrimSpace(p.Created)}}
func uniqueTerms(in []string)[]string{seen:=map[string]bool{};out:=[]string{};for _,v:=range in{s:=strings.TrimSpace(v);if s==""||seen[strings.ToLower(s)]{continue};seen[strings.ToLower(s)]=true;out=append(out,s)};return out}
var _ sources.JobSource=(*Client)(nil)
