package themuse
import ("context";"encoding/json";"fmt";"io";"net/http";"net/url";"strings";"time";"jobsearcher/internal/domain";"jobsearcher/internal/sources")
const defaultURL="https://www.themuse.com/api/public/jobs"
type Client struct{HTTPClient *http.Client;URL string}
func NewClient()*Client{return &Client{HTTPClient:&http.Client{Timeout:30*time.Second},URL:defaultURL}}
func(c *Client)Name()string{return "themuse"}
type response struct{Results []posting `json:"results"`}
type posting struct{ID int64 `json:"id"`;Name string `json:"name"`;Contents string `json:"contents"`;Locations []struct{Name string `json:"name"`} `json:"locations"`;Levels []struct{Name string `json:"name"`} `json:"levels"`;Company struct{Name string `json:"name"`} `json:"company"`;PublicationDate string `json:"publication_date"`;Refs struct{LandingPage string `json:"landing_page"`} `json:"refs"`}
func(c *Client)FetchJobs(ctx context.Context,_ sources.Query)([]domain.Job,error){out:=[]domain.Job{};for page:=1;page<=5;page++{jobs,err:=c.fetchPage(ctx,page);if err!=nil{return out,err};out=append(out,jobs...);if len(jobs)<20{break}};return out,nil}
func(c *Client)fetchPage(ctx context.Context,page int)([]domain.Job,error){u,err:=url.Parse(c.URL);if err!=nil{return nil,err};v:=u.Query();v.Set("page",fmt.Sprint(page));v.Set("category","Engineering");u.RawQuery=v.Encode();req,err:=http.NewRequestWithContext(ctx,http.MethodGet,u.String(),nil);if err!=nil{return nil,err};req.Header.Set("Accept","application/json");req.Header.Set("User-Agent","JobSearcher/1.0");resp,err:=c.HTTPClient.Do(req);if err!=nil{return nil,err};defer resp.Body.Close();body,err:=io.ReadAll(io.LimitReader(resp.Body,32<<20));if err!=nil{return nil,err};if resp.StatusCode<200||resp.StatusCode>=300{return nil,fmt.Errorf("themuse: HTTP %d",resp.StatusCode)};var raw response;if err:=json.Unmarshal(body,&raw);err!=nil{return nil,err};out:=make([]domain.Job,0,len(raw.Results));for _,p:=range raw.Results{if p.ID==0||p.Name==""{continue};out=append(out,normalize(p))};return out,nil}
func normalize(p posting)domain.Job{loc:=[]string{};for _,v:=range p.Locations{loc=append(loc,v.Name)};levels:=[]string{};for _,v:=range p.Levels{levels=append(levels,v.Name)};return domain.Job{ID:fmt.Sprintf("themuse:%d",p.ID),Source:"themuse",Title:strings.TrimSpace(p.Name),Company:strings.TrimSpace(p.Company.Name),URL:strings.TrimSpace(p.Refs.LandingPage),Location:strings.Join(loc,", "),WorkplaceType:inferWorkplace(strings.Join(loc," ")+" "+p.Contents),Seniority:strings.Join(levels,", "),Description:stripHTML(p.Contents),PostedAt:strings.TrimSpace(p.PublicationDate)}}
func inferWorkplace(s string)string{l:=strings.ToLower(s);if strings.Contains(l,"hybrid"){return "Hybrid"};if strings.Contains(l,"remote")||strings.Contains(l,"work from home")||strings.Contains(l,"flexible / remote"){return "Remote"};return ""}
func stripHTML(s string)string{out:=make([]rune,0,len(s));tag:=false;for _,ch:=range s{if ch==60{tag=true;continue};if ch==62{tag=false;continue};if !tag{out=append(out,ch)}};return strings.Join(strings.Fields(string(out))," ")}
var _ sources.JobSource=(*Client)(nil)
